# Generated by Django 3.1.7 on 2021-03-18 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Basliq')),
                ('image', models.ImageField(upload_to='recipe_images', verbose_name='Sekil')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Tam adi')),
                ('email', models.EmailField(max_length=63, verbose_name='E-poct')),
                ('subject', models.CharField(max_length=255, verbose_name='Movzu')),
                ('message', models.TextField(help_text='Bu qutuya mesajinizi daxil edin', verbose_name='Mesaj')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=63, verbose_name='E-poct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(verbose_name='Is_published')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Basliq')),
                ('description', models.TextField(verbose_name='Mezmun')),
                ('image', models.ImageField(upload_to='recipe_images', verbose_name='Sekil')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(verbose_name='Is_published')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, to='stories.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Basliq')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='Qisa Mezmun')),
                ('image', models.ImageField(upload_to='recipe_images', verbose_name='Sekil')),
                ('description', models.TextField(verbose_name='Mezmun')),
                ('is_published', models.BooleanField(verbose_name='Is_published')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='stories.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, to='stories.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Reyiniz')),
                ('email', models.EmailField(max_length=254, verbose_name='Emailiniz')),
                ('website', models.CharField(max_length=127, verbose_name='Website')),
                ('message', models.TextField(help_text='Bu qutuya mesajinizi daxil edin', verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='stories.comment', verbose_name='Parent Comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='stories.recipe', verbose_name='Recipe')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='stories.story', verbose_name='Story')),
            ],
        ),
    ]
