# Generated by Django 3.1.7 on 2021-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210319_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(null=True, verbose_name='Is_published'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(null=True, verbose_name='Is_published'),
        ),
    ]
