# Generated by Django 3.1.7 on 2021-03-20 07:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210319_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mezmun'),
        ),
    ]
