# Generated by Django 3.1.7 on 2021-03-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20210322_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is_published'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is_published'),
        ),
    ]
