# Generated by Django 3.1.7 on 2021-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20210330_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=127, null=True, verbose_name='Basliq'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Basliq'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
