# Generated by Django 3.1.7 on 2021-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20210331_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
