# Generated by Django 3.1.7 on 2021-04-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20210401_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
